service: tictactoe
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: '2'

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-finch
  - serverless-offline

custom:
  stage: ${opt:stage, 'dev'}
  client:
    bucketName: serverless-vue-tictactoe
    distributionFolder: dist

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
            - dynamodb:PutItem
          Resource:
            - "arn:aws:dynamodb:us-east-1:*:*"

  environment:
    CONNECTIONS_TABLE:
      Ref: ConnectionsTable
    GAME_TABLE:
      Ref: GameTable
    # CONNECTIONS_TABLE: 'tictactoe-dev-ConnectionsTable-19O9V9IFVN2CG'
    # GAME_TABLE: 'tictactoe-dev-GameTable-11B0MM70OTQ80'
    APIG_ENDPOINT:
      Fn::Join:
        - ''
        - - Ref: WebsocketsApi
          - .execute-api.
          - Ref: AWS::Region
          - .amazonaws.com/
          - ${self:custom.stage}

functions:
  connection:
    handler: src/backend/connection.handler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  tictactoe:
    handler: src/backend/tictactoe.handler
    events:
      - websocket:
          route: join
      - websocket:
          route: move

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
    GameTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        SSESpecification:
          SSEEnabled: true
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
